// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbhhonjvitrbuvmmesml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaGhvbmp2aXRyYnV2bW1lc21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODI3MzYsImV4cCI6MjA2NTY1ODczNn0.QDqGcSs-nYwM8Vit94vMUhFTGYcDg7evM9R8PJqdh2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);